---
 # optionally find the latest version of goss using the GitHub "API"
 - name: detect latest version
   shell: |
    curl -sIS https://github.com/aelsabbahy/goss/releases/latest | \
      tr -d '\r' | \
      grep -oP '(?<=Location:\s).*' | \
      grep -oP '(?<=v)\d+\.\d+\.\d+'
   register: detected_latest
   when: version == "latest"

 - name: set detected version
   set_fact:
     real_version: "{{ detected_latest.stdout.strip() }}"
   when: version == "latest"

 - name: set specified verison
   set_fact:
     real_version: "{{ version }}"
   when: version != "latest"

 # set play facts
 - name: set facts
   set_fact:
     download_url: "https://github.com/aelsabbahy/goss/releases/download/v{{ real_version }}/goss-linux-amd64"

 # create goss directories
 - name: create goss directories
   file: path={{ item }} state=directory
   with_items:
     - /tmp/degoss
     - /tmp/degoss/bin
     - /tmp/degoss/tests

 # download goss
 - name: install
   get_url:
     url: "{{ download_url }}"
     dest: /tmp/degoss/bin/goss
     mode: 0755

 # deploy test cases
 - name: deploy tests
   copy: src={{ item }} dest=/tmp/degoss/tests/
   with_items: "{{ tests }}"

 # identify names of files to test
 - name: define tests
   set_fact:
    test_files: |
      {% set test_list = [] -%}
      {%- for test in tests -%}
        {%- if '/' in test -%}
          {% set ignored = test_list.append(test.split('/') | last) -%}
        {%- else -%}
          {% set ignored = test_list.append(test) -%}
        {%- endif -%}
      {%- endfor %}
      {{ test_list }}


 # run the tests
 - name: run tests
   goss: executable=/tmp/degoss/bin/goss path="/tmp/degoss/tests/{{ item }}" format="{{ format }}"
   with_items: "{{ test_files }}"

 - name: clean
   file: path=/tmp/degoss state=absent
